### ISSUE TITLE
/dashboard opens even without token

### ISSUE THREAD

**Issue by rishitkamboj** [Rudra-Sankha-Sinhamahapatra/Paytm-payments#1]
![image](https://github.com/Rudra-Sankha-Sinhamahapatra/MoneyTM-Payments-App/assets/102843851/8a977cd9-d1c5-4587-b726-3a5a9f5d4aa4)

This can be avoided by just checking if the token is set if it is not set then just redirect to signup/signin page.

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
ok i will fix it

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
fixed
