### ISSUE TITLE
Can transfer negative amount

### ISSUE THREAD

**Issue by rishitkamboj** [Rudra-Sankha-Sinhamahapatra/Paytm-payments#3]
![image](https://github.com/Rudra-Sankha-Sinhamahapatra/MoneyTM-Payments-App/assets/102843851/57456868-1896-467f-bd0e-d4c3b6c3d777)

I am able to transfer money and that is something that should not be allowed.
You can fix it simply by adding a check if the amount is not a number first and also amount<0

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
ok i will fix this.Thanks for noticing

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
![image](https://github.com/Rudra-Sankha-Sinhamahapatra/MoneyTM-Payments-App/assets/101992909/a1bdad4e-77b6-4362-9852-9d7048b28226)
fixed

![image](https://github.com/Rudra-Sankha-Sinhamahapatra/MoneyTM-Payments-App/assets/101992909/ec5107c2-4698-4d0a-9b8f-0358d98d9a1a)

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
thanks for noticing
