### ISSUE TITLE
Not redirecting to dashboard after successful payment

### ISSUE THREAD

**Issue by rishitkamboj** [Rudra-Sankha-Sinhamahapatra/Paytm-payments#4]
![image](https://github.com/Rudra-Sankha-Sinhamahapatra/MoneyTM-Payments-App/assets/102843851/c50b1e6c-ac81-4cbc-9837-e0ab43c1df77)

It stays at the same page only even after the successful transfwe

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
i will do it later

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
fixed
